### ISSUE TITLE
Only invited users of a board can access it

### ISSUE THREAD

**Issue by wezleytsai** [teamartemis/teamartemis#33]
- Use Parse ACL?
- Board belongs to creator
- Board needs a list of users with admin privileges (includes creator by default)
- Board needs a list of users with access privilege

**Comment by dvc94ch** [comment]
Yes that's going to be an interesting one. I think there are roles in parse, need to figure out how those work. I'm thinking an admin role and a survivor role :)

**Comment by wezleytsai** [comment]
Can roles be different for each board? Can a user be an admin on one board and a "guest" on another through ACL?

**Comment by dvc94ch** [comment]
Don't see why not...

**Comment by wezleytsai** [comment]
oh it's a property of each instance of board - should work
