### ISSUE TITLE
Fix getPosts in Posts services

### ISSUE THREAD

**Issue by wezleytsai** [teamartemis/teamartemis#52]
getPosts currently returns all posts instead just posts for specific boardId

**Comment by kamerynn** [comment]
To send data with GET, it has to be encoded into the url. `$http.get` takes a config object that can have a `params` property. Anything inside those params will get encoded into the url. [Doc is here](https://docs.angularjs.org/api/ng/service/$http#get) (have to scroll up a little to get to the config object)

Parse supports a [`where` query](https://parse.com/docs/rest/guide#queries-query-constraints) that you can specify the key value.

I've tried many variations of the following:

``` javascript
return $http.get('https://api.parse.com/1/classes/Post', {
   params: {
     where: {
       boardId: boardId
     }
   }
})
```

but it's encoding the url wrong. It ends up as `https://api.parse.com/1/classes/Post?where=%7B%22boardId%22:%22edbi0y3Y5c%22%7D` and is flagged as a bad request. I'm not sure what part is being encoded wrong, if there's a more appropriate way to format the `where` object, or if we need to urlencode it in a different way that Angular automatically does
