### ISSUE TITLE
Implement Parse ACL authorization

### ISSUE THREAD

**Issue by wezleytsai** [teamartemis/teamartemis#53]
Parse requests should only be authorized for our web app users
Connects to #32

**Comment by kamerynn** [comment]
Here's a good explanation if anyone is curious: https://www.parse.com/questions/passing-an-acl-with-user-signup-through-rest-api

We'll need to use the session token, so this will have to wait until #41 is finished. But we can basically send a request to update the ACL with the objectId that represents the user we want to allow access, and what kind of access (read/write)

**Comment by wezleytsai** [comment]
nice!
