### ISSUE TITLE
Figure out requirements to allow user to post images and videos

### ISSUE THREAD

**Issue by wezleytsai** [teamartemis/teamartemis#9]

**Comment by wezleytsai** [comment]
Probably can set this up easily by following this:
https://www.parse.com/docs/rest/guide#files

We can associate files with posts. And posts are associated with users.

**Comment by dvc94ch** [comment]
Is using express also ok?

**Comment by dvc94ch** [comment]
So I think this issue involves three parts:
- store/retrive files using express
- add a file input element to board.create
- add a image column to board

**Comment by dvc94ch** [comment]
that was a bad idea using express... I just realized that uploading files requires authentication to avoid Denial of Service attacks
